// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RfidSyncApi.Infrastructure.Persistence;

#nullable disable

namespace RfidSyncApi.Migrations;

[DbContext(typeof(ApplicationDbContext))]
[Migration("20260503000001_InitialCreate")]
partial class InitialCreate
{
    protected override void BuildTargetModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.4")
            .HasAnnotation("Relational:MaxIdentifierLength", 128);

        SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

        modelBuilder.Entity("RfidSyncApi.Domain.Entities.RfidLog", b =>
        {
            b.Property<Guid>("ServerId")
                .ValueGeneratedOnAdd()
                .HasColumnType("uniqueidentifier")
                .HasColumnName("server_id")
                .HasDefaultValueSql("NEWSEQUENTIALID()");

            b.Property<DateTime>("CreatedAt")
                .HasColumnType("datetime2")
                .HasColumnName("created_at");

            b.Property<string>("DeviceId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)")
                .HasColumnName("device_id");

            b.Property<string>("EventType")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)")
                .HasColumnName("event_type");

            b.Property<bool>("IsDeleted")
                .HasColumnType("bit")
                .HasColumnName("is_deleted");

            b.Property<string>("LocalId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)")
                .HasColumnName("local_id");

            b.Property<string>("SiteId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)")
                .HasColumnName("site_id");

            b.Property<string>("TagId")
                .IsRequired()
                .HasMaxLength(64)
                .HasColumnType("nvarchar(64)")
                .HasColumnName("tag_id");

            b.Property<DateTime>("UpdatedAt")
                .IsConcurrencyToken()
                .HasColumnType("datetime2")
                .HasColumnName("updated_at");

            b.Property<string>("UserId")
                .IsRequired()
                .HasMaxLength(128)
                .HasColumnType("nvarchar(128)")
                .HasColumnName("user_id");

            b.Property<int>("Version")
                .HasDefaultValue(1)
                .HasColumnType("int")
                .HasColumnName("version");

            b.HasKey("ServerId");
            b.HasIndex("DeviceId").HasDatabaseName("IX_rfid_logs_device_id");
            b.HasIndex("UpdatedAt").HasDatabaseName("IX_rfid_logs_updated_at");
            b.HasIndex("TagId").HasDatabaseName("IX_rfid_logs_tag_id");
            b.HasIndex("SiteId").HasDatabaseName("IX_rfid_logs_site_id");
            b.HasIndex("DeviceId", "LocalId").IsUnique().HasDatabaseName("UX_rfid_logs_device_local");
            b.HasIndex("DeviceId", "UpdatedAt").HasDatabaseName("IX_rfid_logs_device_updated");
            b.ToTable("rfid_logs");
        });
#pragma warning restore 612, 618
    }
}
